id: A46B964F9
title: fCC81
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:53:24.016512
  last_modified_at: 2022-05-27 14:53:24.016520
